url: https://aleksnavratil.github.io
baseurl: /

# Site settings
title: Sushi Warehouse
email: aleks.navratil@gmail.com
description: "A giant pile of NJ gas station sushi"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Mike Kelly
  pic: mike
  position: CEO and Founder
  social:
    - title: twitter
      url: https://twitter.com/carlthegnarl
    - title: linkedin
      url: 

- name: Aleks Navratil
  pic: aleks
  position: Chief Data Scientist
  social:
    - title: twitter
      url: https://twitter.com/carlthegnarl
    - title: facebook
      url: http://aleksnavratil.com/
    - title: linkedin
      url: https://www.linkedin.com/in/aleksnavratil

- name: Luke Kowalczyk
  pic: luke
  position: Chief Technical Officer
  social:
    - title: twitter
      url: http://www.cs.columbia.edu/~luke/
    - title: linkedin
      url: https://www.linkedin.com/pub/lucas-kowalczyk/26/5b7/b76

- name: Satoshi Nakamoto
  pic: satoshi
  position: Chief Sushi Officer
  social:
    - title: twitter
      url: https://twitter.com/carlthegnarl

- name: Doug Bienstock
  pic: doug
  position: Chief Security Officer
  social:
    - title: twitter
      url: https://twitter.com/carlthegnarl
    - title: linkedin
      url: https://www.linkedin.com/pub/douglas-bienstock/61/b00/353

- name: Adam Halbert
  pic: adam
  position: Chief Visionary at Sushi X Research Labs
  social:
    - title: twitter
      url: https://twitter.com/carlthegnarl
    - title: linkedin
      url: https://www.linkedin.com/pub/adam-halbert/aa/7a1/985

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/carlthegnarl
  - title: facebook
    url: http://aleksnavratil.com/
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/sushi
  - title: github
    url: http://github.com/aleksnavratil

# Postal address (add as many lines as necessary)
address:
  - line: 1 Astor Place,
  - line: New York, New York, 10010

# Build settings
markdown: kramdown
permalink: pretty
